// <auto-generated />
using CleanArchitecture.DataAccess.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("CleanArchitecture.Core.Models.Alert", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstSensorReadingDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSensorReadingDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlertId");

                    b.HasIndex("DeviceSerialNumber");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Models.Device", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstRegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedSecret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("SerialNumber");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Models.DeviceReading", b =>
                {
                    b.Property<int>("DeviceReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CarbonMonoxide")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Humidity")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("ReceivedDateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedDateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperature")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("DeviceReadingId");

                    b.HasIndex("DeviceSerialNumber");

                    b.ToTable("DeviceReadings");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Models.DeviceRegistration", b =>
                {
                    b.Property<int>("DeviceRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceRegistrationId");

                    b.HasIndex("DeviceSerialNumber");

                    b.ToTable("DeviceRegistrations");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Models.Alert", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Models.DeviceReading", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("CleanArchitecture.Core.Models.DeviceRegistration", b =>
                {
                    b.HasOne("CleanArchitecture.Core.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });
#pragma warning restore 612, 618
        }
    }
}
